spring:
  security:
    oauth2:
     resourceserver:
        jwt:
          jwr-set-uri: http://localhost:8080/auth/realms/shop/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/shop
  application:
    name: E-Commerce
  datasource:
    username: 'root'
    driver-class-name : com.mysql.cj.jdbc.Driver
    password: 'CalM4t23@'
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

#keycloak:
  #resource: shop
  #realm: shop

keycloak:
  realm: shop
  auth-server-url: http://localhost:8080/auth
  resource: shop
  #bearer-only: true

logging:
  level:
    it:
      matt&i: DEBUG
    org:
      springframework: INFO

server:
  compression:
    enabled: 'true'
  port: '8000'